//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSStartupSkeleton.WebAPI.SQLDBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountMgtDBEntities : DbContext
    {
        public AccountMgtDBEntities()
            : base("name=AccountMgtDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User_Account> User_Account { get; set; }
        public virtual DbSet<User_Contacts> User_Contacts { get; set; }
        public virtual DbSet<User_Details> User_Details { get; set; }
    }
}
