//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSStartupSkeleton.WebAPI.SQLDBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Account
    {
        public User_Account()
        {
            this.User_Details = new HashSet<User_Details>();
        }
    
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<User_Details> User_Details { get; set; }
    }
}
