//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJSStartupSkeleton.WebAPI.SQLDBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Details
    {
        public System.Guid Id { get; set; }
        public System.Guid User_Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string companyName { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> Zip { get; set; }
    
        public virtual User_Account User_Account { get; set; }
    }
}
